### PR TITLE
Issue 59 fix

### LINKED ISSUE #59: TypeError: Illegal kind "string" for plugin ""
Getting the title'd error why trying to run styleguidist.

I'm not sure what's going on.  I tried to troubleshoot myself, but was unsuccessful.

```
> project@1.0.0 styleguide-server /PROJECT
> styleguidist server

Listening at http://localhost:3000

webpack built 25ce954cda50e939fb85 in 823ms
Hash: 25ce954cda50e939fb85
Version: webpack 1.12.2
Time: 823ms
          Asset     Size  Chunks       Chunk Names
build/bundle.js  45.1 kB       0       main
chunk    {0} build/bundle.js (main) 7.69 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js 3.27 kB {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] (webpack)-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
    [4] (webpack)-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0} [built]
    [5] (webpack)-hot-middleware/client-overlay.js 883 bytes {0} [built]
    [6] (webpack)-hot-middleware/process-update.js 2.93 kB {0} [built]

ERROR in ./~/react-styleguidist/src/index.js
Module build failed: TypeError: Illegal kind "string" for plugin ""
    at PluginManager.add (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/plugin-manager.js:196:13)
    at File.buildTransformers (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/PROJECT/node_modules/react-styleguidist/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/PROJECT/node_modules/react-styleguidist/node_modules/babel-loader/index.js:71:12)
 @ multi main
```

### PR DESCRIPTION
**Pull request by mik01aj**
#59

### CODE REVIEW

File: src/make-webpack-config.js [hunk 1]
```diff
@@ -5,15 +5,14 @@ var ExtractTextPlugin = require('extract-text-webpack-plugin');
...
 var config = require('../src/utils/config');
 
 module.exports = function(env) {
 	var isProd = env === 'production';
 	var cssLoader = 'css?modules&importLoaders=1&localIdentName=ReactStyleguidist-[name]__[local]!postcss';
 
-	var codeMirrorPath = getInstalledPath('codemirror', true);
-	var reactTransformPath = getInstalledPath('babel-plugin-react-transform', true);
+	var codeMirrorPath = path.dirname(require.resolve('codemirror/package.json'));
+	var reactTransformPath = require.resolve('babel-plugin-react-transform');
```
Comment (sapegin) [inline src/make-webpack-config.js]: Why `package.json` in the first and just package name in the second?

Comment (mik01aj) [inline src/make-webpack-config.js]: because `require.resolve(moduleName)` returns path to the `index` module inside the package. For react transform it's ok, but for codemirror it's not, so I get the path to `package.json` and go up one level.

Comment (sapegin) [inline src/make-webpack-config.js]: Can we wrap it in a function and always do `path.dirname(require.resolve('packagename/package.json'));`?

**Comment by mik01aj** [comment]
@sapegin see the new commit.

**Comment by sapegin** [comment]
That’s much better, thanks!

**Comment by mik01aj** [comment]
@sapegin, good! So when you merge this please look at https://github.com/sapegin/react-styleguidist/pull/67 and make a new release with these bugfixes. :)
